export const LABELS = {
  fr: {
    // Navigation
    home:"Accueil", stats:"Stats", profile:"Profil",
    // Humeurs
    howAreYou:"Comment tu te sens ?",
    energized:"Énergisé", calm:"Calme", tired:"Fatigué", stressed:"Stressé",
    // Habitudes
    habits:"Habitudes du jour",
    habitTitles:{ 1:"Boire 2L d'eau", 2:"10 min méditation", 3:"30 min marche", 4:"Journaling soir", 5:"Coucher avant 23h" },
    habitTimes:{ 1:"Toute la journée", 2:"Matin • 7:00", 3:"Midi • 12:30", 4:"Soir • 21:00", 5:"Nuit • 22:45" },
    habitXP:{ 1:"+10 XP", 2:"+20 XP", 3:"+30 XP", 4:"+15 XP", 5:"+25 XP" },
    habitsDone:(n,m)=>`${n}/${m} habitudes`,
    // Piliers
    pillars:"Tes piliers bien-être",
    sleep:"Sommeil", hydration:"Hydratation", movement:"Mouvement", serenity:"Sérénité",
    // Pas
    stepsTitle:"Mes pas aujourd'hui",
    stepsGoal:"Objectif : 10 000 pas",
    stepsSave:"Valider",
    stepsPlaceholder:"Nombre de pas...",
    stepsMotivation:(s)=>s>=10000?"🔥 Incroyable !":s>=7500?"💪 Très bien !":s>=5000?"👍 Objectif atteint !":"🚶 Continue !",
    // Nutrition
    nutrition:"🥦 L'alimentation : ton pilier N°1",
    nutritionWarn:"⚠️ 70% de tes résultats viennent de ce que tu manges",
    sponsored:"SPONSORISÉ",
    sponsorNote:"VitaZen perçoit une commission · Partenaires sélectionnés",
    nutritionTips:{
      default:"Une alimentation équilibrée est la base de tous tes résultats.",
      weightloss:"Déficit de 300 kcal/j, protéines à 1,6g/kg, légumes à volonté.",
      muscle:"Surplus de 200 kcal/j, protéines à 2g/kg, repas autour de l'entraînement.",
      energy:"3 repas structurés, céréales complètes, oméga-3, évite les sucres rapides.",
    },
    // Earn Premium
    earnTitle:"🏆 Gagne 1 mois Pro gratuit",
    earnInfo:(h,d)=>`${h} habitudes + 5 000 pas/jour pendant ${d} jours consécutifs`,
    earnDesc:(n)=>`Encore ${n} jour${n>1?"s":""} parfait${n>1?"s":""}…`,
    earnDone:"🎉 Félicitations, tu as gagné !",
    perfectDay:"✅ Journée parfaite !",
    // Stats
    thisWeek:"Cette semaine", today:"Aujourd'hui",
    towardsPremium:"Vers le Premium mérité",
    perfectDaysLabel:"jours parfaits consécutifs",
    // Profil
    level:"Niveau", xp:"XP", streak:"Streak",
    language:"Langue",
    editProfile:"✏️ Modifier", saveProfile:"Sauvegarder ✓",
    myIMC:"IMC", idealWeight:"Poids idéal",
    height:"Taille (cm)", weight:"Poids (kg)",
    gender:"Genre", male:"Homme", female:"Femme", neutral:"Non précisé",
    goals:"Mes objectifs",
    goalLabels:{
      weightloss:"Perdre du poids", muscle:"Prendre du muscle", endurance:"Améliorer l'endurance",
      sleep:"Mieux dormir", stress:"Réduire le stress", energy:"Booster l'énergie",
    },
    imcLabels:{ u:"Insuffisance pondérale", n:"Poids normal ✓", o:"Surpoids", ob:"Obésité" },
    completeProfile:"Complète ton profil !",
    completeProfileSub:"Pour des conseils vraiment personnalisés",
    profileSaved:"✅ Profil sauvegardé !",
    // IA
    aiName:"VitaAI", aiSub:"Coach IA personnalisé",
    aiThinking:"Analyse en cours...",
    aiPlaceholder:"Pose ta question à VitaAI...",
    aiError:"Clé Groq manquante — vérifie VITE_GROQ_API_KEY sur Vercel.",
    // Pro
    proActive:"✦ PRO ACTIF", goPro:"✦ Passer Pro",
    seePlans:"Voir les plans →",
    moreLeft:(n)=>`Encore ${n} jours parfaits !`,
    activateFreeNow:"🎉 Active ton mois gratuit !",
    autoEarn:(n)=>`🏆 ${n} jours parfaits = 1 mois offert`,
    renewIn:"Renouvellement dans 28 jours",
    proRenew:"VitaAI illimitée · Zéro pub · Rapports PDF",
    // Modals
    earnedTitle:"Félicitations !",
    earnedSub:"Tu as gagné 1 mois Premium gratuit",
    activateFree:"Activer mon mois gratuit →",
    noCard:"Aucune carte bancaire requise",
    proFeatures:["✨ VitaAI illimitée","🚫 Zéro publicité","📊 Rapports PDF hebdo","⚡ Accès prioritaire"],
    premiumTitle:"VitaZen Pro",
    premiumEarn:"🏆 30 jours parfaits = 1 mois offert",
    monthly:"Mensuel", yearly:"Annuel",
    monthlyPrice:"4,99€", yearlyPrice:"2,99€",
    monthlySub:"Sans engagement", yearlySub:"35,88€/an • -40%",
    startMonthly:"Commencer à 4,99€/mois →",
    startYearly:"Commencer à 2,99€/mois →",
    trialNote:"Essai 7 jours gratuit · Annulation à tout moment",
    // Notifs
    notifTitle:"Rappel quotidien", notifSub:"1 message par jour max",
    activateNotif:"Activer", testNotif:"Tester", notifSent:"✓ Envoyée !",
    notifGranted:"✓ Activées", notifDenied:"✗ Bloquées", notifPending:"En attente",
    // Auth
    loginTitle:"Bon retour 👋", signupTitle:"Crée ton compte gratuitement",
    emailPlaceholder:"Ton adresse email",
    passwordPlaceholder:"Mot de passe (6 caractères min)",
    namePlaceholder:"Ton prénom",
    loginBtn:"Se connecter →", signupBtn:"Créer mon compte →",
    switchToSignup:"S'inscrire", switchToLogin:"Se connecter",
    noAccount:"Pas encore de compte ?", hasAccount:"Déjà un compte ?",
    footerNote:"Tes données sont sécurisées et ne sont jamais revendues. 🔒",
    // Divers
    logout:"Se déconnecter",
    darkMode:"🌙 Mode sombre", exportData:"📤 Exporter",
    feedback:"💬 Feedback", help:"❓ Aide",
    days:["L","M","M","J","V","S","D"],
    dateLocale:"fr-FR",
  },
  en: {
    home:"Home", stats:"Stats", profile:"Profile",
    howAreYou:"How are you feeling?",
    energized:"Energized", calm:"Calm", tired:"Tired", stressed:"Stressed",
    habits:"Today's Habits",
    habitTitles:{ 1:"Drink 2L water", 2:"10 min meditation", 3:"30 min walk", 4:"Evening journal", 5:"Bed before 11pm" },
    habitTimes:{ 1:"All day", 2:"Morning • 7:00", 3:"Noon • 12:30", 4:"Evening • 9pm", 5:"Night • 10:45pm" },
    habitXP:{ 1:"+10 XP", 2:"+20 XP", 3:"+30 XP", 4:"+15 XP", 5:"+25 XP" },
    habitsDone:(n,m)=>`${n}/${m} habits`,
    pillars:"Your wellness pillars",
    sleep:"Sleep", hydration:"Hydration", movement:"Movement", serenity:"Serenity",
    stepsTitle:"My steps today",
    stepsGoal:"Goal: 10,000 steps",
    stepsSave:"Save",
    stepsPlaceholder:"Number of steps...",
    stepsMotivation:(s)=>s>=10000?"🔥 Amazing!":s>=7500?"💪 Great!":s>=5000?"👍 Goal reached!":"🚶 Keep going!",
    nutrition:"🥦 Nutrition: Your #1 Pillar",
    nutritionWarn:"⚠️ 70% of your results come from what you eat",
    sponsored:"SPONSORED",
    sponsorNote:"VitaZen earns a commission · Selected partners",
    nutritionTips:{
      default:"A balanced diet is the foundation of all your wellness results.",
      weightloss:"300 kcal deficit/day, protein at 1.6g/kg, vegetables freely.",
      muscle:"200 kcal surplus/day, protein at 2g/kg, meals around training.",
      energy:"3 structured meals, whole grains, omega-3, avoid fast sugars.",
    },
    earnTitle:"🏆 Earn 1 free Pro month",
    earnInfo:(h,d)=>`${h} habits + 5,000 steps/day for ${d} consecutive days`,
    earnDesc:(n)=>`${n} more perfect day${n>1?"s":""}…`,
    earnDone:"🎉 Congratulations, you've earned it!",
    perfectDay:"✅ Perfect day!",
    thisWeek:"This week", today:"Today",
    towardsPremium:"Towards earned Premium",
    perfectDaysLabel:"consecutive perfect days",
    level:"Level", xp:"XP", streak:"Streak",
    language:"Language",
    editProfile:"✏️ Edit", saveProfile:"Save ✓",
    myIMC:"BMI", idealWeight:"Ideal weight",
    height:"Height (cm)", weight:"Weight (kg)",
    gender:"Gender", male:"Male", female:"Female", neutral:"Prefer not to say",
    goals:"My goals",
    goalLabels:{
      weightloss:"Lose weight", muscle:"Build muscle", endurance:"Improve endurance",
      sleep:"Sleep better", stress:"Reduce stress", energy:"Boost energy",
    },
    imcLabels:{ u:"Underweight", n:"Normal weight ✓", o:"Overweight", ob:"Obese" },
    completeProfile:"Complete your profile!",
    completeProfileSub:"For truly personalized advice",
    profileSaved:"✅ Profile saved!",
    aiName:"VitaAI", aiSub:"Personalized AI coach",
    aiThinking:"Analyzing...",
    aiPlaceholder:"Ask VitaAI anything...",
    aiError:"Groq key missing — check VITE_GROQ_API_KEY on Vercel.",
    proActive:"✦ PRO ACTIVE", goPro:"✦ Go Pro",
    seePlans:"See plans →",
    moreLeft:(n)=>`${n} more perfect days!`,
    activateFreeNow:"🎉 Activate your free month!",
    autoEarn:(n)=>`🏆 ${n} perfect days = 1 month free`,
    renewIn:"Renewal in 28 days",
    proRenew:"Unlimited VitaAI · Zero ads · PDF reports",
    earnedTitle:"Congratulations!",
    earnedSub:"You've earned 1 free Premium month",
    activateFree:"Activate my free month →",
    noCard:"No credit card required",
    proFeatures:["✨ Unlimited VitaAI","🚫 Zero ads","📊 Weekly PDF reports","⚡ Priority access"],
    premiumTitle:"VitaZen Pro",
    premiumEarn:"🏆 30 perfect days = 1 month free",
    monthly:"Monthly", yearly:"Yearly",
    monthlyPrice:"€4.99", yearlyPrice:"€2.99",
    monthlySub:"No commitment", yearlySub:"€35.88/yr • -40%",
    startMonthly:"Start at €4.99/month →",
    startYearly:"Start at €2.99/month →",
    trialNote:"7-day free trial · Cancel anytime",
    notifTitle:"Daily reminder", notifSub:"1 message per day max",
    activateNotif:"Enable", testNotif:"Test", notifSent:"✓ Sent!",
    notifGranted:"✓ Enabled", notifDenied:"✗ Blocked", notifPending:"Pending",
    loginTitle:"Welcome back 👋", signupTitle:"Create your free account",
    emailPlaceholder:"Your email address",
    passwordPlaceholder:"Password (6 characters min)",
    namePlaceholder:"Your first name",
    loginBtn:"Log in →", signupBtn:"Create my account →",
    switchToSignup:"Sign up", switchToLogin:"Log in",
    noAccount:"No account yet?", hasAccount:"Already have an account?",
    footerNote:"Your data is secure and never sold. 🔒",
    logout:"Log out",
    darkMode:"🌙 Dark mode", exportData:"📤 Export",
    feedback:"💬 Feedback", help:"❓ Help",
    days:["M","T","W","T","F","S","S"],
    dateLocale:"en-GB",
  },
  es: {
    home:"Inicio", stats:"Stats", profile:"Perfil",
    howAreYou:"¿Cómo te sientes?",
    energized:"Energizado", calm:"Tranquilo", tired:"Cansado", stressed:"Estresado",
    habits:"Hábitos de hoy",
    habitTitles:{ 1:"Beber 2L agua", 2:"10 min meditación", 3:"30 min caminata", 4:"Diario tarde", 5:"Dormir antes 23h" },
    habitTimes:{ 1:"Todo el día", 2:"Mañana • 7:00", 3:"Mediodía • 12:30", 4:"Tarde • 21:00", 5:"Noche • 22:45" },
    habitXP:{ 1:"+10 XP", 2:"+20 XP", 3:"+30 XP", 4:"+15 XP", 5:"+25 XP" },
    habitsDone:(n,m)=>`${n}/${m} hábitos`,
    pillars:"Tus pilares de bienestar",
    sleep:"Sueño", hydration:"Hidratación", movement:"Movimiento", serenity:"Serenidad",
    stepsTitle:"Mis pasos hoy",
    stepsGoal:"Objetivo: 10.000 pasos",
    stepsSave:"Guardar",
    stepsPlaceholder:"Número de pasos...",
    stepsMotivation:(s)=>s>=10000?"🔥 ¡Increíble!":s>=7500?"💪 ¡Muy bien!":s>=5000?"👍 ¡Objetivo alcanzado!":"🚶 ¡Sigue así!",
    nutrition:"🥦 Alimentación: tu Pilar N°1",
    nutritionWarn:"⚠️ El 70% de tus resultados vienen de lo que comes",
    sponsored:"PATROCINADO",
    sponsorNote:"VitaZen recibe comisión · Socios seleccionados",
    nutritionTips:{
      default:"Una alimentación equilibrada es la base de todos tus resultados.",
      weightloss:"Déficit de 300 kcal/d, proteínas a 1,6g/kg, verduras a voluntad.",
      muscle:"Superávit de 200 kcal/d, proteínas a 2g/kg, comidas alrededor del entrenamiento.",
      energy:"3 comidas estructuradas, cereales integrales, omega-3, evita azúcares rápidos.",
    },
    earnTitle:"🏆 Gana 1 mes Pro gratis",
    earnInfo:(h,d)=>`${h} hábitos + 5.000 pasos/día durante ${d} días consecutivos`,
    earnDesc:(n)=>`${n} día${n>1?"s":""} perfecto${n>1?"s":""} más…`,
    earnDone:"🎉 ¡Felicidades, lo has ganado!",
    perfectDay:"✅ ¡Día perfecto!",
    thisWeek:"Esta semana", today:"Hoy",
    towardsPremium:"Hacia el Premium merecido",
    perfectDaysLabel:"días perfectos consecutivos",
    level:"Nivel", xp:"XP", streak:"Racha",
    language:"Idioma",
    editProfile:"✏️ Editar", saveProfile:"Guardar ✓",
    myIMC:"IMC", idealWeight:"Peso ideal",
    height:"Altura (cm)", weight:"Peso (kg)",
    gender:"Género", male:"Hombre", female:"Mujer", neutral:"No especificar",
    goals:"Mis objetivos",
    goalLabels:{
      weightloss:"Perder peso", muscle:"Ganar músculo", endurance:"Mejorar resistencia",
      sleep:"Dormir mejor", stress:"Reducir estrés", energy:"Aumentar energía",
    },
    imcLabels:{ u:"Bajo peso", n:"Peso normal ✓", o:"Sobrepeso", ob:"Obesidad" },
    completeProfile:"¡Completa tu perfil!",
    completeProfileSub:"Para consejos realmente personalizados",
    profileSaved:"✅ ¡Perfil guardado!",
    aiName:"VitaAI", aiSub:"Coach IA personalizado",
    aiThinking:"Analizando...",
    aiPlaceholder:"Pregunta a VitaAI...",
    aiError:"Clave Groq faltante — verifica VITE_GROQ_API_KEY en Vercel.",
    proActive:"✦ PRO ACTIVO", goPro:"✦ Ir a Pro",
    seePlans:"Ver planes →",
    moreLeft:(n)=>`¡${n} días perfectos más!`,
    activateFreeNow:"🎉 ¡Activa tu mes gratis!",
    autoEarn:(n)=>`🏆 ${n} días perfectos = 1 mes gratis`,
    renewIn:"Renovación en 28 días",
    proRenew:"VitaAI ilimitada · Cero anuncios · PDF",
    earnedTitle:"¡Felicidades!",
    earnedSub:"Has ganado 1 mes Premium gratis",
    activateFree:"Activar mi mes gratis →",
    noCard:"No se requiere tarjeta",
    proFeatures:["✨ VitaAI ilimitada","🚫 Cero publicidad","📊 Informes PDF semanales","⚡ Acceso prioritario"],
    premiumTitle:"VitaZen Pro",
    premiumEarn:"🏆 30 días perfectos = 1 mes gratis",
    monthly:"Mensual", yearly:"Anual",
    monthlyPrice:"4,99€", yearlyPrice:"2,99€",
    monthlySub:"Sin compromiso", yearlySub:"35,88€/año • -40%",
    startMonthly:"Empezar a 4,99€/mes →",
    startYearly:"Empezar a 2,99€/mes →",
    trialNote:"Prueba 7 días gratis · Cancelar cuando quieras",
    notifTitle:"Recordatorio diario", notifSub:"1 mensaje por día máx",
    activateNotif:"Activar", testNotif:"Probar", notifSent:"✓ ¡Enviado!",
    notifGranted:"✓ Activadas", notifDenied:"✗ Bloqueadas", notifPending:"Pendiente",
    loginTitle:"Bienvenido de nuevo 👋", signupTitle:"Crea tu cuenta gratis",
    emailPlaceholder:"Tu dirección de email",
    passwordPlaceholder:"Contraseña (6 caracteres mín)",
    namePlaceholder:"Tu nombre",
    loginBtn:"Iniciar sesión →", signupBtn:"Crear mi cuenta →",
    switchToSignup:"Registrarse", switchToLogin:"Iniciar sesión",
    noAccount:"¿No tienes cuenta?", hasAccount:"¿Ya tienes cuenta?",
    footerNote:"Tus datos están seguros y nunca se venden. 🔒",
    logout:"Cerrar sesión",
    darkMode:"🌙 Modo oscuro", exportData:"📤 Exportar",
    feedback:"💬 Comentarios", help:"❓ Ayuda",
    days:["L","M","X","J","V","S","D"],
    dateLocale:"es-ES",
  },
};

export const getLabel = (lang) => LABELS[lang] || LABELS.fr;
